"""
Enterprise Incidents API Endpoint — Phase 4/MDM Update

Exposes PostgreSQL-backed enterprise incidents generated by AI risk matching across
suppliers, components, factories, shipments, and inventory buffers.
"""

import logging
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.core.security import get_current_user, UserPrincipal
from app.db.models.enterprise_incident import EnterpriseIncident
from app.risk.incident_generator import EnterpriseIncidentGenerator
from app.news.pipeline import NewsPipeline

logger = logging.getLogger("api.incidents")
router = APIRouter()


@router.get("", summary="List all Enterprise Incidents for tenant")
@router.get("/", summary="List all Enterprise Incidents for tenant")
def list_enterprise_incidents(
    current_user: UserPrincipal = Depends(get_current_user),
    db: Session = Depends(get_db),
    status_filter: Optional[str] = Query(default=None, alias="status"),
    risk_level: Optional[str] = Query(default=None),
    limit: int = Query(default=50, ge=1, le=200),
) -> Dict[str, Any]:
    """
    Returns structured enterprise incidents from PostgreSQL, scoped to the authenticated tenant.
    """
    user_id = current_user.user_id
    query = db.query(EnterpriseIncident).filter(
        (EnterpriseIncident.company_user_id == user_id) | (EnterpriseIncident.company_user_id.is_(None))
    )
    
    if status_filter:
        query = query.filter(EnterpriseIncident.status == status_filter.upper())
    if risk_level:
        query = query.filter(EnterpriseIncident.risk_level == risk_level.upper())
        
    incidents = query.order_by(EnterpriseIncident.created_at.desc()).limit(limit).all()

    # If DB has 0 incidents for tenant, run initial generation from stored disruption news
    if not incidents:
        try:
            pipeline = NewsPipeline()
            recent_news = pipeline.get_recent_disruptions(db, limit=20)
            if recent_news:
                generator = EnterpriseIncidentGenerator(db)
                incidents = generator.generate_incidents_from_news(recent_news)
        except Exception as exc:
            logger.warning(f"Auto incident generation on empty list failed: {exc}")

    results = []
    for inc in incidents:
        results.append({
            "id": inc.id,
            "company_user_id": inc.company_user_id or user_id,
            "news_article_id": inc.news_article_id,
            "news_title": inc.news_title,
            "news_url": inc.news_url,
            "news_source": inc.news_source,
            "incident_title": inc.incident_title,
            "incident_description": inc.incident_description,
            "affected_supplier": inc.affected_supplier,
            "affected_factory": inc.affected_factory,
            "affected_components": inc.affected_components or [],
            "affected_products": inc.affected_products or [],
            "affected_inventory": inc.affected_inventory,
            "affected_shipment": inc.affected_shipment,
            "risk_score": inc.risk_score,
            "risk_level": inc.risk_level,
            "business_impact": inc.business_impact,
            "financial_impact": inc.financial_impact,
            "estimated_delay": inc.estimated_delay,
            "confidence": inc.confidence,
            "root_cause": inc.root_cause,
            "recommended_actions": inc.recommended_actions or [],
            "alternative_suppliers": inc.alternative_suppliers or [],
            "recovery_plan": inc.recovery_plan,
            "timeline": inc.timeline or [],
            "status": inc.status,
            "created_at": inc.created_at.isoformat() if inc.created_at else None,
            "updated_at": inc.updated_at.isoformat() if inc.updated_at else None,
        })

    return {
        "total": len(results),
        "incidents": results
    }


@router.get("/{incident_id}", summary="Get Enterprise Incident Details")
def get_enterprise_incident(
    incident_id: str,
    current_user: UserPrincipal = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get detailed enterprise incident record by UUID.
    """
    inc = db.query(EnterpriseIncident).filter(EnterpriseIncident.id == incident_id).first()
    if not inc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Enterprise incident '{incident_id}' not found."
        )

    return {
        "id": inc.id,
        "company_user_id": inc.company_user_id or current_user.user_id,
        "news_article_id": inc.news_article_id,
        "news_title": inc.news_title,
        "news_url": inc.news_url,
        "news_source": inc.news_source,
        "incident_title": inc.incident_title,
        "incident_description": inc.incident_description,
        "affected_supplier": inc.affected_supplier,
        "affected_factory": inc.affected_factory,
        "affected_components": inc.affected_components or [],
        "affected_products": inc.affected_products or [],
        "affected_inventory": inc.affected_inventory,
        "affected_shipment": inc.affected_shipment,
        "risk_score": inc.risk_score,
        "risk_level": inc.risk_level,
        "business_impact": inc.business_impact,
        "financial_impact": inc.financial_impact,
        "estimated_delay": inc.estimated_delay,
        "confidence": inc.confidence,
        "root_cause": inc.root_cause,
        "recommended_actions": inc.recommended_actions or [],
        "alternative_suppliers": inc.alternative_suppliers or [],
        "recovery_plan": inc.recovery_plan,
        "timeline": inc.timeline or [],
        "status": inc.status,
        "created_at": inc.created_at.isoformat() if inc.created_at else None,
        "updated_at": inc.updated_at.isoformat() if inc.updated_at else None,
    }


@router.post("/generate", summary="Trigger manual Enterprise Incident generation")
def generate_enterprise_incidents(
    current_user: UserPrincipal = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Runs the AI incident generator over recent disruption news and updates PostgreSQL.
    """
    pipeline = NewsPipeline()
    recent_news = pipeline.get_recent_disruptions(db, limit=30)
    
    generator = EnterpriseIncidentGenerator(db)
    generated = generator.generate_incidents_from_news(recent_news)

    return {
        "status": "success",
        "generated_count": len(generated),
        "message": f"Successfully generated {len(generated)} enterprise incidents in PostgreSQL."
    }
