import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LifeBuoy, Book, MessageSquare, ChevronDown, ChevronRight, Search, Plus, CheckCircle2, Send, Ticket } from 'lucide-react';
import PageHeader from '../../components/supplier/shared/PageHeader';
import EmptyState from '../../components/supplier/shared/EmptyState';
import StatusBadge from '../../components/supplier/shared/StatusBadge';
import FileUploadZone from '../../components/supplier/shared/FileUploadZone';
import { createSupportTicket, getSupportTickets } from '../../services/supplierApi';

const FAQS = [
  { q: 'How do I update my production capacity?', a: 'Navigate to Production Capacity in the sidebar. Fill in the utilization sliders and output fields, then click Save Changes.' },
  { q: 'When will my account be approved?', a: 'Administrator approval typically takes 1–2 business days. You will receive an email notification once your account is reviewed.' },
  { q: 'How are my AI performance scores calculated?', a: 'Scores are generated by the SupplyShield AI engine based on your operational data, incident history, delivery performance, and market signals. They update automatically as data is processed.' },
  { q: 'Can I edit my AI scores?', a: 'No. AI scores are read-only and generated by our engine. The best way to improve scores is to keep your data up to date, report incidents promptly, and maintain consistent production and shipment records.' },
  { q: 'How do I report a supply chain disruption?', a: 'Go to Incident Reporting in the sidebar. Select the incident category and severity, provide a description, and optionally upload supporting photos or documents.' },
  { q: 'How long does it take for my data updates to reflect in the platform?', a: 'Most updates are processed in real-time. AI score recalculations may take up to 24 hours after significant data changes.' },
  { q: 'Who can see my supplier data?', a: 'Your data is visible only to authorized SupplyShield AI administrators and is protected under enterprise-grade security protocols.' },
];

const TICKET_CATEGORIES = ['General Inquiry', 'Account Issue', 'Technical Problem', 'Data Dispute', 'Integration Support', 'Billing', 'Other'];
const TICKET_PRIORITIES = ['Low', 'Medium', 'High', 'Urgent'];

function FaqItem({ faq }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: '1px solid #F3F4F6' }}>
      <button onClick={() => setOpen(!open)}
        style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: '16px 20px', background: 'none', border: 'none', cursor: 'pointer', textAlign: 'left' }}>
        <span style={{ fontSize: 13.5, fontWeight: 600, color: '#111827' }}>{faq.q}</span>
        <ChevronDown size={16} color="#9CA3AF" style={{ flexShrink: 0, transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} />
      </button>
      <AnimatePresence>
        {open && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} style={{ overflow: 'hidden' }}>
            <div style={{ padding: '0 20px 16px', fontSize: 13.5, color: '#6B7280', lineHeight: 1.7 }}>{faq.a}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function SupportCenter() {
  const [activeSection, setActiveSection] = useState('faq');
  const [query, setQuery] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [ticket, setTicket] = useState({ subject: '', category: '', priority: 'Medium', description: '', files: [] });
  const [myTickets, setMyTickets] = useState([]);
  const [loadingTickets, setLoadingTickets] = useState(true);

  const loadTickets = useCallback(async () => {
    setLoadingTickets(true);
    try {
      const res = await getSupportTickets();
      const items = Array.isArray(res) ? res : (res?.items || []);
      setMyTickets(items);
    } catch (err) {
      console.error('Failed to load support tickets:', err);
    } finally {
      setLoadingTickets(false);
    }
  }, []);

  useEffect(() => { loadTickets(); }, [loadTickets]);

  const set = (k) => (v) => setTicket((p) => ({ ...p, [k]: typeof v === 'object' && v.target ? v.target.value : v }));

  async function handleSubmit(e) {
    e.preventDefault();
    if (!ticket.subject?.trim() || !ticket.description?.trim()) return;
    setSubmitting(true);
    try {
      const subj = ticket.subject.trim();
      const desc = ticket.description.trim();
      const payload = {
        subject: subj.length >= 5 ? subj : `${subj} (Support Request)`,
        description: desc.length >= 10 ? desc : `${desc} (Reported via Support Center)`,
        category: ticket.category || 'General Inquiry',
        priority: (ticket.priority || 'MEDIUM').toUpperCase(),
      };
      await createSupportTicket(payload);
      setSubmitted(true);
      setTimeout(() => {
        setSubmitted(false);
        setTicket({ subject: '', category: '', priority: 'Medium', description: '', files: [] });
        loadTickets();
      }, 3000);
    } catch (err) {
      console.error('Submit ticket error:', err);
      alert(err.message || 'Failed to submit ticket');
    } finally {
      setSubmitting(false);
    }
  }

  const filteredFaqs = FAQS.filter((f) => !query || f.q.toLowerCase().includes(query.toLowerCase()) || f.a.toLowerCase().includes(query.toLowerCase()));
  const inputSt = { width: '100%', border: '1px solid #E5E7EB', borderRadius: 7, padding: '9px 12px', fontSize: 13.5, outline: 'none', boxSizing: 'border-box' };
  const labelSt = { fontSize: 11, fontWeight: 700, color: '#6B7280', display: 'block', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.04em' };

  return (
    <div>
      <PageHeader title="Support Center" description="Find answers, documentation, and contact our support team" />

      {/* Section tabs */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 24 }}>
        {[
          { id: 'faq', label: 'FAQs', icon: Book },
          { id: 'ticket', label: 'Raise a Ticket', icon: MessageSquare },
          { id: 'contact', label: 'Contact Support', icon: LifeBuoy },
        ].map(({ id, label, icon: Icon }) => (
          <button key={id} onClick={() => setActiveSection(id)}
            style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '9px 18px', borderRadius: 9, border: `1.5px solid ${activeSection === id ? '#2563EB' : '#E5E7EB'}`, background: activeSection === id ? '#EFF6FF' : 'white', color: activeSection === id ? '#2563EB' : '#6B7280', fontSize: 13.5, fontWeight: activeSection === id ? 700 : 400, cursor: 'pointer', transition: 'all 0.15s' }}>
            <Icon size={15} />{label}
          </button>
        ))}
      </div>

      {/* FAQ Section */}
      {activeSection === 'faq' && (
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
          <div style={{ position: 'relative', maxWidth: 420, marginBottom: 20 }}>
            <Search size={15} style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: '#9CA3AF', pointerEvents: 'none' }} />
            <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search FAQs…"
              style={{ ...inputSt, paddingLeft: 36 }} onFocus={(e) => e.target.style.borderColor = '#2563EB'} onBlur={(e) => e.target.style.borderColor = '#E5E7EB'} />
          </div>
          <div className="card" style={{ overflow: 'hidden' }}>
            {filteredFaqs.length === 0 ? (
              <EmptyState type="search" title="No FAQs match your search" description="Try different keywords or raise a support ticket." />
            ) : (
              filteredFaqs.map((faq, i) => <FaqItem key={i} faq={faq} />)
            )}
          </div>
        </motion.div>
      )}

      {/* Raise Ticket Section */}
      {activeSection === 'ticket' && (
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
          <div className="card" style={{ padding: '24px 28px', maxWidth: 680 }}>
            {submitted ? (
              <div style={{ textAlign: 'center', padding: '40px 0' }}>
                <div style={{ width: 64, height: 64, background: '#ECFDF5', borderRadius: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px' }}>
                  <CheckCircle2 size={32} color="#10B981" />
                </div>
                <h3 style={{ fontSize: 18, fontWeight: 700, color: '#111827', marginBottom: 8 }}>Ticket Submitted!</h3>
                <p style={{ fontSize: 13, color: '#6B7280' }}>Our support team will respond within 1 business day.</p>
              </div>
            ) : (
              <form onSubmit={handleSubmit}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                  <div style={{ gridColumn: 'span 2' }}>
                    <label style={labelSt}>Subject *</label>
                    <input style={inputSt} value={ticket.subject} onChange={set('subject')} placeholder="Brief description of your issue" required onFocus={(e) => e.target.style.borderColor='#2563EB'} onBlur={(e) => e.target.style.borderColor='#E5E7EB'} />
                  </div>
                  <div>
                    <label style={labelSt}>Category</label>
                    <select style={{ ...inputSt, cursor: 'pointer' }} value={ticket.category} onChange={set('category')}>
                      <option value="">Select category…</option>
                      {TICKET_CATEGORIES.map((c) => <option key={c}>{c}</option>)}
                    </select>
                  </div>
                  <div>
                    <label style={labelSt}>Priority</label>
                    <div style={{ display: 'flex', gap: 8 }}>
                      {TICKET_PRIORITIES.map((p) => {
                        const colors = { Low: '#10B981', Medium: '#F59E0B', High: '#EF4444', Urgent: '#7F1D1D' };
                        return (
                          <button key={p} type="button" onClick={() => set('priority')(p)}
                            style={{ flex: 1, padding: '7px 4px', borderRadius: 7, border: `1.5px solid ${ticket.priority === p ? colors[p] : '#E5E7EB'}`, background: ticket.priority === p ? `${colors[p]}18` : 'white', color: ticket.priority === p ? colors[p] : '#6B7280', fontSize: 12, fontWeight: ticket.priority === p ? 700 : 400, cursor: 'pointer', transition: 'all 0.15s' }}>
                            {p}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                  <div style={{ gridColumn: 'span 2' }}>
                    <label style={labelSt}>Description *</label>
                    <textarea style={{ ...inputSt, resize: 'vertical' }} rows={5} value={ticket.description} onChange={set('description')} placeholder="Describe your issue in detail. Include any steps to reproduce the problem, expected behavior, and actual behavior." required onFocus={(e) => e.target.style.borderColor='#2563EB'} onBlur={(e) => e.target.style.borderColor='#E5E7EB'} />
                  </div>
                  <div style={{ gridColumn: 'span 2' }}>
                    <label style={labelSt}>Attachments (optional)</label>
                    <FileUploadZone onFiles={(f) => set('files')(Array.from(f))} multiple hint="Attach screenshots or relevant files" />
                  </div>
                </div>
                <button type="submit" disabled={submitting}
                  style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '10px 22px', border: 'none', borderRadius: 9, fontSize: 13.5, fontWeight: 700, background: submitting ? '#9CA3AF' : 'linear-gradient(135deg, #2563EB, #7C3AED)', color: 'white', cursor: submitting ? 'not-allowed' : 'pointer' }}>
                  <Send size={15} />{submitting ? 'Submitting…' : 'Submit Ticket'}
                </button>
              </form>
            )}
          </div>
        </motion.div>
      )}

      {/* Contact Section */}
      {activeSection === 'contact' && (
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 16 }}>
            {[
              { icon: '📧', label: 'Email Support', value: 'support@supplyshield.ai', desc: 'Typical response: < 24 hours', color: '#2563EB', bg: '#EFF6FF' },
              { icon: '💬', label: 'Live Chat', value: 'Available Mon–Fri, 9am–6pm EST', desc: 'Real-time support for urgent issues', color: '#10B981', bg: '#ECFDF5' },
              { icon: '📞', label: 'Phone Support', value: '+1 (800) SUPPLY-AI', desc: 'Enterprise plans only', color: '#7C3AED', bg: '#F5F3FF' },
              { icon: '📖', label: 'Documentation', value: 'docs.supplyshield.ai', desc: 'Full API and platform docs', color: '#F59E0B', bg: '#FFFBEB' },
            ].map(({ icon, label, value, desc, color, bg }) => (
              <div key={label} className="card" style={{ padding: '20px 22px' }}>
                <div style={{ fontSize: 28, marginBottom: 14 }}>{icon}</div>
                <h3 style={{ fontSize: 14, fontWeight: 700, color: '#111827', marginBottom: 4 }}>{label}</h3>
                <p style={{ fontSize: 13, color, fontWeight: 600, marginBottom: 4 }}>{value}</p>
                <p style={{ fontSize: 12, color: '#9CA3AF' }}>{desc}</p>
              </div>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  );
}
